name: Deploy ke GitHub Pages

on:
  push:
    branches:
      - main   # jalankan workflow saat push ke branch main
  workflow_dispatch:

permissions:
  contents: read      # default minimal
  pages: write        # izin menulis ke GitHub Pages
  id-token: write     # untuk verifikasi OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artefak
        uses: actions/upload-pages-artifact@v1
        with:
          path: .   # folder berisi index.html dan file lain

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
