# .github/workflows/deploy.yml
name: Deploy Static Site

on:
  push:
    branches:
      - main   # setiap kali push ke branch main
  workflow_dispatch:  # bisa juga dijalankan manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Report status
        run: echo "✅ File statis siap dideploy"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # root repo berisi index.html
