name: Deploy Absensi App

on:
  push:
    branches: ["main"]   # jalan setiap ada commit ke main
  workflow_dispatch:      # bisa dijalankan manual juga

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node (opsional)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build step
        run: |
          echo "Tidak ada proses build karena hanya index.html"
          mkdir -p ./dist
          cp index.html ./dist/
          cp data-siswa.js ./dist/

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Report build status
        run: |
          gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
            -F github_run_id="$GITHUB_RUN_ID" \
            -F conclusion="success"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [report-build-status]
    steps:
      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
